version: '3'

services:
  db:
    build: .
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "pompom"
      POSTGRES_PASSWORD: "pompom"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    command: ["sh", "-c", "while true; do sleep 1; done"]
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: anus@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pompom
    depends_on:
      - db
volumes:
  pgadmin4_data:
  db_data: